apiVersion: v2
name: my-nginx
version: &version 0.1.0
appVersion: &appVersion latest

dependencies:
  # ghcr.io/jackydalong/charts/my-nginx:0.1.0
  - name: my-nginx
    version: *version
    repository: oci://ghcr.io/jackydalong/charts
    alias: my-app
    
