cert-manager:
  installCRDs: true
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      memory: 64Mi
  webhook:
    resources:
      requests:
        cpu: 10m
        memory: 25Mi
      limits:
        memory: 25Mi
  cainjector:
    resources:
      requests:
        cpu: 10
        memory: 50Mi
      limits:
        memory: 50Mi
  prometheus:
    enabled: true
