apiVersion: v2
type: application
name: vault
version: &version "1.27.0" # UPGRADED: Using a newer, stable operator version.
appVersion: &appVersion "1.19.0" # UPGRADED: Set Vault image version
description: Kubernetes operator for Hashicorp Vault
icon: https://avatars.githubusercontent.com/u/129937617
keywords:
  - vault
  - hashicorp
  - secret
  - operator
home: https://bank-vaults.dev
sources:
  - https://github.com/hashicorp/vault
  - https://github.com/bank-vaults/vault-operator
  - https://artifacthub.io/packages/helm/vault-operator/vault-operator
maintainers:
  - name: Bank Vaults Maintainers
    email: team@bank-vaults.dev

dependencies:
  - name: vault-operator
    version: *version
    repository: oci://ghcr.io/bank-vaults/helm-charts
    alias: vault