apiVersion: v1
kind: Secret
metadata:
  name: jacky-ghcr-repo
  namespace: argocd
  labels:
    vault-injection: enabled
    argocd.argoproj.io/secret-type: repository
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    vault.security.banzaicloud.io/vault-addr: https://vault-cn.vault.svc.cluster.local:8200
    vault.security.banzaicloud.io/vault-tls-secret: vault-cn-tls
    vault.security.banzaicloud.io/vault-serviceaccount: default
stringData:
  # MUST match the domain/path in your Chart.yaml dependency
  # If Chart.yaml has: oci://ghcr.io/jackydalong/charts
  # Use this URL (without oci://):
  url: ghcr.io/jackydalong/charts
  
  # GitHub Username
  username: jackydalong
  
  # GitHub PAT (Settings -> Developer Settings -> Personal access tokens)
  # Needs scope: 'read:packages'
  password: vault:secret/data/kubernetes/mgmt/jacky-ghcr#token
  
  # Crucial for OCI registries
  enableOCI: "true"
  name: jackydalong-charts