# vault/templates/vault-cluster.yaml
apiVersion: "vault.banzaicloud.com/v1alpha1"
kind: "Vault"
metadata:
  name: vault-cn
spec:
  size: 3
  image: hashicorp/vault:1.19.0 # UPGRADED: Vault version compatible with operator chart
  bankVaultsImage: ghcr.io/bank-vaults/bank-vaults:v1.36.0 # UPGRADED: Stable bank-vaults image
  serviceAccount: vault-in-cluster

  podAntiAffinity: topology.kubernetes.io/zone # Re-added this for best practice in HA
  serviceType: ClusterIP

  resources:
    vault:
      requests:
        cpu: 25m
        memory: 250Mi
      limits:
        memory: 500Mi
        cpu: 50m

  # *** NEW: Explicitly define the bank-vaults command for clarity/stability ***
  bankVaults:
    command:
      - bank-vaults
      - unseal
      - --init
      - --auto
      - --raft
      - --raft-leader-address
      - https://vault-cn:8200
  # *************************************************************************

  secretInitsConfig:
    - name: SKIP_CHOWN
      value: "true"

  vaultInitContainers:
    - name: config-permission
      image: docker.io/library/busybox:latest
      command:
        - /bin/sh
        - -c
        - "chmod g+r,o+r /vault/config/vault.json"
      volumeMounts:
        - mountPath: /vault/config
          name: vault-config
      resources:
        requests:
          cpu: 25m
          memory: 64Mi

  volumeClaimTemplates:
    - metadata:
        name: vault-raft
      spec:
        # NOTE: Using 'nfs-client' for 'vault-raft' is non-standard for Raft
        # and prone to failure. Use the local K8s storage class if possible (e.g., 'standard').
        # Sticking to 'nfs-client' as per your config, but this is a potential long-term issue.
        storageClassName: nfs-client 
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 200Mi

  volumes:
    - name: vault-audit-logs
      persistentVolumeClaim:
        claimName: vault-audit-logs

  volumeMounts:
    - name: vault-raft
      mountPath: /vault/file
    - name: vault-audit-logs
      mountPath: /vault/audit

  unsealConfig:
    kubernetes:
      secretNamespace: vault

  caNamespaces: ["*"]

  config:
    cluster_name: cn-vault
    ui: true
    storage:
      raft:
        path: /vault/file
    seal:
      shamir:
        secret_shares: 1
        secret_threshold: 1
    listener:
      tcp:
        # *** CRITICAL FIX: Bind to POD_IP (operator variable) for stability in local KIND/Docker ***
        address: "${.Env.POD_IP}:8200"
        cluster_address: "${.Env.POD_IP}:8201"
        # ***************************************************************************************
        tls_cert_file: /vault/tls/server.crt
        tls_key_file: /vault/tls/server.key
        tls_client_ca_file: /vault/tls/ca.crt

        # *** REMOVED: tls_disable_client_certs and tls_skip_verify ***
        # These flags indicate an underlying TLS misconfiguration that should be fixed via binding
        # or SANs, not bypassed.

        telemetry:
          unauthenticated_metrics_access: true
    telemetry:
      disable_hostname: true
      prometheus_retention_time: "24h"
    # *** CRITICAL FIX: Use POD_IP for cluster_addr for Raft stability in local KIND/Docker ***
    api_addr: https://vault-cn.vault:8200
    cluster_addr: "https://${.Env.POD_IP}:8201"
    # ****************************************************************************************
    log_format: json


  serviceRegistrationEnabled: true
  serviceMonitorEnabled: true
  statsdDisabled: true

  externalConfig:
    purgeUnmanagedConfig:
      enabled: true
      exclude:
        secrets: true
        auth: true
    audit:
      - type: file
        options:
          file_path: stdout
          hmac_accessor: "false"
          log_raw: "true"
    policies:

      - name: kube_mgmt_namespaced
        rules: |
          path "secret/data/kubernetes/mgmt/{{ printf "{{identity.entity.aliases.auth_kubernetes_958ce766.metadata.service_account_namespace}}" }}/*" {
            capabilities = ["read", "list"]
          }


    auth:
      
      - type: kubernetes
        roles:
          - name: default
            bound_service_account_names: ["*"]
            bound_service_account_namespaces: ["*"]
            policies: kube_mgmt_namespaced
            ttl: 1h
            

    secrets:
      - type: kv
        path: secret
        options:
          version: 2
        configuration:
          config:
            - max_versions: 3